# Generated by Django 2.1.3 on 2019-05-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='Body',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='Title',
        ),
    ]
